### PR TITLE
vegan::commsimulator() is .Defunct in vegan_2.5-1

### PR DESCRIPTION
**Pull request by jarioksa**
`commsimulator()` was deprecated in vegan 2.2-0 and made defunct in
2.5-0. The current change gives an exact replacement of the old
function with `simulate.nullmodel()` of current vegan.

Without this PR the following fails:
```r
library(nodiv)
data(coquettes)
Nodesig(coquettes, method="quasiswap")
```

### CODE REVIEW

**Comment by mkborregaard** [comment]
Thanks! I'll roll a new version and send to CRAN. There's no way of mentioning that this depends on a specific version of vegan, is there?

**Comment by jarioksa** [comment]
Actually it adds a dependency, but on such an old version as `vegan (>= 2.2)` which is from 2014. At that version we introduced the new `simulate(nullmodel())` framework, but still kept the old `commsimulator` available. It only became defunct in 2.5-1 this month.

**Comment by mkborregaard** [comment]
Great.

**Comment by mkborregaard** [comment]
Version 1.2 with this PR incorporated is on CRAN now.

**Pull request merged**
